apiVersion: apps/v1 # for versions before 1.8.0 use apps/v1beta1
kind: Deployment
metadata:
  name: visualsearch-deployment
spec:
  selector:
    matchLabels:
      app: visualsearch
  replicas: 1 # tells deployment to run 2 pods matching the template
  template: # create pods using pod definition in this template
    metadata:
      labels:
        app: visualsearch
    spec:
      containers:
      - name: visualsearch
        image: gcr.io/visualsearch-232720/sjsu/spring/2019/296:visualsearch
        command: ["/bin/sh","-c"]
        args: ["/opt/conda/bin/conda install jupyter -y --quiet  && /opt/conda/bin/jupyter notebook --notebook-dir=/visual/notebook --ip='*' --port=8888 --no-browser --allow-root"]
        ports:
        - containerPort: 8888
        securityContext:
          privileged: true
          capabilities:
            add:
              - SYS_ADMIN
        lifecycle:
          postStart:
            exec:
              command: ["gcsfuse", "-o", "nonempty,rw,allow_other","--implicit-dirs","--file-mode","777","--dir-mode","777", "visualsearch-image-bucket", "/visual"]
          preStop:
            exec:
              command: ["fusermount", "-u", "/visual"]
---
apiVersion: v1
kind: Service
metadata:
  name: visualsearch-service
  labels:
    app: visualsearch
spec:
  type: LoadBalancer
  ports:
  - protocol: TCP
    port: 8888
    targetPort: 8888
  selector:
    app: visualsearch